import type { Course, LabChallenge } from "./types";

// Stable course configuration. Student, resource, assessment, and activity data
// are loaded from the authenticated API.
export const courses: Course[] = [
  {
    id: "course-java",
    code: "JAVA",
    title: "Object-Oriented Programming through JAVA",
    description: "KGR25 theory and laboratory work organized unit by unit.",
    accent: "cyan",
    faculty: "KGR Faculty",
    enrolled: 0,
    units: [
      { number: 1, title: "Object oriented thinking and Java Basics" },
      { number: 2, title: "Inheritance, Packages and Interfaces" },
      { number: 3, title: "Exception handling and Multithreading" },
      { number: 4, title: "Event Handling" },
      { number: 5, title: "Applets" },
    ],
    experiments: [
      { number: 1, title: "Installation & Orientation" },
      { number: 2, title: "Quadratic Equation Solutions" },
      { number: 3, title: "Matrix Multiplication" },
      { number: 4, title: "Inheritance & Abstract Classes" },
      { number: 5, title: "Shape Abstract Class" },
      { number: 6, title: "Method & Constructor Overloading" },
      { number: 7, title: "Method Overriding" },
      { number: 8, title: "Currency Converter (Interfaces)" },
      { number: 9, title: "User Defined Exception Handling" },
      { number: 10, title: "Integer Division Exception" },
      { number: 11, title: "Multi-threading (Producer-Consumer)" },
      { number: 12, title: "Inter Thread Communication" },
      { number: 13, title: "File Splitter" },
      { number: 14, title: "File Information Reader" },
      { number: 15, title: "JDBC Database Operations" },
      { number: 16, title: "Traffic Light Simulation" },
      { number: 17, title: "Mouse Event Handling" },
      { number: 18, title: "Key Event Handlers" },
      { number: 19, title: "Simple Calculator App" },
      { number: 20, title: "Basic Applet Message" },
      { number: 21, title: "Factorial Applet" },
    ],
  },
  {
    id: "course-dbms",
    code: "DBMS",
    title: "Database Management Systems",
    description: "KGR25 database theory, SQL practice, assessments, and experiments.",
    accent: "amber",
    faculty: "KGR Faculty",
    enrolled: 0,
    units: [
      { number: 1, title: "Database System Applications & ER Diagrams" },
      { number: 2, title: "Relational Model & Relational Algebra" },
      { number: 3, title: "SQL Queries, Constraints & Triggers" },
      { number: 4, title: "Transaction Concept & Concurrency" },
      { number: 5, title: "Data Storage & Indexing Methods" },
    ],
    experiments: [
      { number: 1, title: "Concept design with E-R Model" },
      { number: 2, title: "Relational Model" },
      { number: 3, title: "Normalization" },
      { number: 4, title: "Practicing DDL commands" },
      { number: 5, title: "Practicing DML commands" },
      { number: 6, title: "Complex Querying" },
      { number: 7, title: "Aggregate functions & Views" },
      { number: 8, title: "Triggers" },
      { number: 9, title: "Procedures" },
      { number: 10, title: "Usage of Cursors" },
    ],
  },
];

// General unassigned practice remains available as a lightweight orientation
// workspace. Faculty-assigned practice and labs use the unit coursework flow.
export const labChallenges: LabChallenge[] = [
  {
    id: "practice-java-orientation",
    courseId: "course-java",
    language: "java",
    title: "Java editor orientation",
    topic: "Classes and console output",
    statement: "Complete a small Java class with a main method and print a result.",
    concept: "A Java application begins at the public static void main entry point.",
    constraints: ["Use a Main class", "Keep braces balanced", "Print at least one value"],
    sampleInput: "",
    expectedOutput: "Java structure checks passed.",
    starterCode: "public class Main {\n  public static void main(String[] args) {\n    System.out.println(\"Ready\");\n  }\n}",
    hint: "Keep the class and main method declarations before adding the solution.",
  },
  {
    id: "practice-dbms-orientation",
    courseId: "course-dbms",
    language: "sql",
    title: "SQL editor orientation",
    topic: "Read-only queries",
    statement: "Write a SELECT query and validate its basic structure.",
    concept: "SELECT identifies result columns and FROM identifies the source relation.",
    constraints: ["Terminate the statement with a semicolon", "Use balanced parentheses"],
    sampleInput: "",
    expectedOutput: "SQL structure checks passed.",
    starterCode: "SELECT *\nFROM students;",
    hint: "Start with SELECT and FROM, then add filters or ordering.",
  },
];
